name: random
description: Let Fortuna decide for you!
publish_to: 'none'
version: 2.0.0+2
environment:
  sdk: ">=2.13.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  fonts:
    - family: ProductSansBold
      fonts:
         - asset: assets/fonts/ProductSansBold.ttf
